name: Qt6 test builds CI

# TODO: revise cache usage, we don't care about it too much now.

on: [pull_request, push]

env:
  VCPKG_COMMIT: 8dddc6c899ce6fdbeab38b525a31e7f23cb2d5bb
  VCPKG_DEST_MACOS: /Users/runner/qbt_tools/vcpkg
  VCPKG_DEST_WIN: C:\qbt_tools\vcpkg
  # default features include zstd, which must be excluded until https://bugreports.qt.io/browse/QTBUG-93604 is fixed
  # see the related comment in the main CMakeLists.txt for more information.
  QTBASE_FEATURES: "[brotli,concurrent,core,dbus,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,widgets]"

jobs:

  ci_windows_static:
    name: Windows + vcpkg

    strategy:
      matrix:
        build_type: ["Release", "Debug"]
      fail-fast: false

    runs-on: windows-2019

    defaults:
      run:
        shell: pwsh

    steps:
    - name: checkout repository
      uses: actions/checkout@v2

    # - ninja is needed for building qBittorrent (because it's preferable, not a hard requirement)
    - name: install additional required packages with chocolatey
      run: |
        choco install ninja
    - name: setup vcpkg (cached, if possible)
      uses: lukka/run-vcpkg@v7
      with:
        vcpkgDirectory: ${{ env.VCPKG_DEST_WIN }}
        vcpkgGitCommitId: ${{ env.VCPKG_COMMIT }}
        setupOnly: true
        doNotCache: true

    # clear buildtrees after each package installation to reduce disk space requirements
    - name: install dependencies via vcpkg
      run: |
        $packages = `
          "boost-circular-buffer:x64-windows-static",
          "libtorrent:x64-windows-static",
          "qtbase${{ env.QTBASE_FEATURES }}:x64-windows-static",
          "qtsvg:x64-windows-static",
          "qttools:x64-windows-static",
          "qttranslations:x64-windows-static"
        ${{ env.RUNVCPKG_VCPKG_ROOT }}/vcpkg.exe upgrade `
            --no-dry-run `
            --host-triplet=x64-windows-static
        foreach($package in $packages)
        {
          ${{ env.RUNVCPKG_VCPKG_ROOT }}/vcpkg.exe install $package `
            --clean-after-build `
            --host-triplet=x64-windows-static
        }
    # NOTE: this is necessary to correctly find and use cl.exe with the Ninja generator for now
    - name: setup devcmd
      uses: ilammy/msvc-dev-cmd@v1

    - name: build qBittorrent (${{ matrix.build_type }})
      shell: cmd
      run: |
        cmake -B build -G "Ninja" ^
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ^
          -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_DEST_WIN }}\scripts\buildsystems\vcpkg.cmake ^
          -DVCPKG_TARGET_TRIPLET=x64-windows-static ^
          -DVERBOSE_CONFIGURE=ON ^
          -DMSVC_RUNTIME_DYNAMIC=OFF ^
          --graphviz=build\target_graph.dot
        cmake --build build

    - name: install qBittorrent
      run: |
        cmake --install build --prefix qBittorrent_x64-windows-static_${{ matrix.build_type }}
        
    - name: upload artifact as zip
      uses: actions/upload-artifact@v2
      with:
        name: qBittorrent-CI_Windows-x64-static
        path: |
          build/compile_commands.json
          build/install_manifest.txt
          build/target_graph.dot
          qBittorrent_x64-windows-static_${{ matrix.build_type }}
